feat(pocket-ecs-codepipeline): Make codepipeline steps extendable
Pocket/terraform-modules pull request #748
Opened 2022-01-05 17:53 UTC by mmiermans

# Goal
Allow CodePipeline steps to be added or changed.

## Todos
- [ ] Outstanding todo
- [x] Completed todo

## Review
- [ ] Security @ReviewerA
- [ ] Test coverage @ReviewerC
- [ ] ...

## Reference

Related PR:
* https://github.com/Pocket/data-flows/pull/12

## Implementation Decisions

2022-01-06 21:06 UTC, jpetto reviewed
if the test case here is representational of an actual use case (in that there is no internal class data needed to construct additional deploy actions), i think i'd prefer if we took the route of adding an optional config value. would love input from others too.

aside from the access level changes, i quite like the refactoring done here - moving small bits of logic out of `createCodePipeline` and into little helper functions.

2022-01-06 21:12 UTC, jpetto commented
this may be the start of a larger conversation around how we want to handle app-specific needs in regards to infrastructure. there are a few patterns i think we can evaluate here - class config (which we use now and is a bit clunky), non-private/extensible classes (as this PR is doing), or pre-build hooks (e.g. `const cpl = new PocketECSCodePipeline(...config); cpl.addDeploySteps([step1, step2]); cpl.createCodePipeline();`)

2022-01-06 23:22 UTC, jpetto requested changes
i like the simplicity of this targeted approach much better 😄

2022-01-06 23:22 UTC, jpetto commented on src/pocket/PocketECSCodePipeline.ts
> +    runOrder: number
if these are only called once, and since everything else is hard-coded, would the code be simpler to hard-code the `runOrder` as well?

2022-01-06 23:22 UTC, jpetto commented on src/pocket/PocketECSCodePipeline.ts
> +    ...(this.config.postDeployStage ? [this.config.postDeployStage] : []),
what do you think about making `config.postDeployStage` an array? (perhaps with a rename to `postDeployStages`.) would make it a little more extensible and simplify this line of code as well.

2022-01-07 20:39 UTC, kkyeboah reviewed
looks good, nice work extending this construct, I like both suggestions from @jpetto

2022-01-07 20:40 UTC, kkyeboah commented
also, you'll need to rebase your change on main to get the verified commit check to pass.

2022-01-14 05:48 UTC, mmiermans commented on src/pocket/PocketECSCodePipeline.ts
> +  postDeployStages?: codepipeline.CodepipelineStage[];
Note: I added both `preDeployStages` and `postDeployStages`. When I was iterating on the custom stage it was convenient to run it first, to not have to wait 5 minutes for the deployment to finish. I can imagine `preDeployStages` would also be useful to run automated tests.

2022-01-14 20:25 UTC, kkyeboah approved these changes
looks good to me 👍. has this been tested in dev?

2022-01-14 21:18 UTC, jpetto approved these changes
looking solid to me. same question as @kkyeboah - has this been tested on dev?

2022-01-15 00:36 UTC, mmiermans commented
Yeah, I've tested it successfully in dev.

2022-01-15 00:38 UTC, merged